version: "3.7"
services:
  back: 
    image: node:12.18-alpine
    command: yarn run dev
    env_file:
      - ./back/common.env
    ports:
      - 3333:3333
      - 9229:9229
    working_dir: /usr/app/
    volumes:
      - ./back:/usr/app/
    depends_on:
      - db
    
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
      POSTGRES_DB: gestaousuarios
    volumes:
      - ./banco/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  front: 
    image: node:12.18-alpine
    command: yarn run start
    ports:
      - 4200:4200
      - 9876:9876
    working_dir: /usr/app/
    volumes:
      - ./front:/usr/app/