# Realiza o build, teste e deploy do back-end no Heroku

name: Deploy Back-end

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Instalação de dependencias
      - name: Dependencias
        run: |
          cd back2
          yarn install

      # Testes unitários
      - name: Testes unitários
        run: |
          (cd back2 && yarn run test)

      # Realiza build da aplicação na pasta dist
      - name: Build
        run: |
          cd back2
          yarn run build:prod

      # Realiza deploy da aplicação no Heroku
      - name: Deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "gestao-de-usuarios"
          heroku_email: "gianbarzano@gmail.com"
          appdir: back2
